improve recover script

diff --git a/ansible/roles/archlinux/install/pacstrap/templates/btrfs-system-recover.j2 b/ansible/roles/archlinux/install/pacstrap/templates/btrfs-system-recover.j2
--- a/ansible/roles/archlinux/install/pacstrap/templates/btrfs-system-recover.j2
+++ b/ansible/roles/archlinux/install/pacstrap/templates/btrfs-system-recover.j2
@@ -2,12 +2,20 @@
 
 set -e
 
-[ "$EUID" -ne 0 ] && echo "require root" && exit 1
+if [ "$EUID" -ne 0 ]; then
+    echo "ERROR: require root"
+    exit 1
+fi
+
+if ! mount | grep "on / type btrfs" | grep "@snapshots"; then
+    echo "ERROR: Script only work if booted from btrfs snapshot volume"
+    exit 1
+fi
 
 check() {
     [ "$?" -eq "0" ] || echo "Error: Recovery failed"
     [ -d /tmp/btrfs-recover/{{ btrfs_sys_subvolume }}/boot ] || echo "Warning: System is not bootable anymore"
-    rm -d /tmp/btrfs-recover >/dev/null
+    rm -d /tmp/btrfs-recover 2>/dev/null
 }
 trap check SIGHUP SIGINT SIGTERM EXIT
 
@@ -19,7 +27,10 @@ fi
 recover=$(find /tmp/btrfs-recover/{{ btrfs_sys_snapshot_subvolume }} -maxdepth 2 -name "info.xml" | fzf --preview 'cat {}' | sed 's/\/info.xml$//g') || exit 1
 [ -z "$recover" ] && exit 1
 
-[ ! -d $recover/snapshot ] && echo "[ERROR] SnapshotNotFound: $recover/snapshot" && exit 1
+if [ ! -d $recover/snapshot ]; then
+    echo "[ERROR] SnapshotNotFound: $recover/snapshot"
+    exit 1
+fi
 
 echo "process system recover ... (may take several seconds)"
 rm -rf /tmp/btrfs-recover/{{ btrfs_sys_subvolume }}/{*,.*} >/dev/null 2>&1 || echo "clear bad btrfs system root"  # return always true
